# Smoke-test config: one epoch, few steps, skip validation
vocab_size: 32000
d_model: 512
num_heads: 8
num_layers: 6
max_seq_length: 128
dropout_rate: 0.1
learning_rate: 0.0001
batch_size: 32
num_epochs: 1
tokenizer_path: tokenizer
max_steps_per_epoch: 5
skip_validation: True
log_every: 1
seed: 42
